[build-system]
requires = [
    "setuptools",
    "nltk",
    "textblob",
    "numpy",
    "langdetect",
    "wordcloud",
    "pillow",
    "matplotlib",
    "pandas"
]
build-backend = "setuptools.build_meta"
