{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOTy4ngvCn7ek+4oqFnv6Lf",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/DianaVG3110/authors_clasiffier/blob/main/Sentiment_Analysis.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "\"\"\"Código para interpretar el sentimiento de una canción\"\"\"\n",
        "! pip install nltk\n",
        "import nltk\n",
        "nltk.download('punkt')\n",
        "nltk.download('stopwords')\n",
        "with open(\"/AlejandroSanz.txt\", 'r', encoding='utf-8') as file:\n",
        "    text = file.read()\n",
        "from nltk.tokenize import word_tokenize\n",
        "from nltk.corpus import stopwords\n",
        "import string\n",
        "\n",
        "# Tokenización\n",
        "words = word_tokenize(text.lower())  # Convierte a minúsculas\n",
        "\n",
        "# Eliminación de signos de puntuación y palabras irrelevantes\n",
        "stop_words = set(stopwords.words('spanish'))\n",
        "words = [word for word in words if word.isalnum() and word not in stop_words]\n",
        "# La lógica para determinar la categoría de sentimiento\n",
        "# Puedes usar análisis de palabras clave, reglas específicas, etc.\n",
        "\n",
        "\n",
        "\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "smSHRuaK-OtX",
        "outputId": "96769f0b-483e-48cf-bee9-409f652f767d"
      },
      "execution_count": 29,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)\n",
            "Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.7)\n",
            "Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.3.2)\n",
            "Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2023.6.3)\n",
            "Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.66.1)\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "[nltk_data] Downloading package punkt to /root/nltk_data...\n",
            "[nltk_data]   Package punkt is already up-to-date!\n",
            "[nltk_data] Downloading package stopwords to /root/nltk_data...\n",
            "[nltk_data]   Package stopwords is already up-to-date!\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#sentiment_category = \"positivo\"\n",
        "sentiment_category = [\"positivo\", \"negativo\"]\n",
        "#document = (words, sentiment_category)\n",
        "#document = [(w,s) for w in words for s in sentiment_category]\n",
        "#Crea la estructura de datos necesaria para entrenar un modelo o realizar análisis.\n",
        "positiv = [\"amiga\",\"feliz\",\"fuerza\",\"corazón\",\"amaré\",\"besó\",\"cielo\",\"iluminó\"]\n",
        "negative = [\"apagan\",\"soledad\",\"crujen\",\"llueve\",\"derramando\",\"silencio\",\"feróz\"]\n",
        "\n",
        "\n",
        "\n"
      ],
      "metadata": {
        "id": "MJK6gehXIJ60"
      },
      "execution_count": 35,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "\"\"\"Ejemplo de código\"\"\"\n",
        "! pip install nltk\n",
        "import nltk\n",
        "from nltk.corpus import movie_reviews\n",
        "nltk.download('movie_reviews')\n",
        "documents = [(list(movie_reviews.words(fileid)), category)\n",
        "             for category in movie_reviews.categories()\n",
        "             for fileid in movie_reviews.fileids(category)]\n",
        "import random\n",
        "random.shuffle(documents)\n",
        "training_set = documents[:1500]\n",
        "test_set = documents[1500:]\n",
        "\n",
        "\"\"\"Función para extraer las caractéristicas básicas del mensaje\"\"\"\n",
        "\n",
        "all_words = nltk.FreqDist(w.lower() for w in movie_reviews.words())\n",
        "word_features = list(all_words)[:3000]\n",
        "\n",
        "def document_features(document):\n",
        "    document_words = set(document)\n",
        "    features = {}\n",
        "    for word in word_features:\n",
        "        features[word] = (word in document_words)\n",
        "    return features\n",
        "featuresets = [(document_features(d), c) for (d, c) in training_set]\n",
        "classifier = nltk.NaiveBayesClassifier.train(featuresets)\n",
        "test_featuresets = [(document_features(d), c) for (d, c) in test_set]\n",
        "accuracy = nltk.classify.accuracy(classifier, test_featuresets)\n",
        "print(\"Accuracy:\", accuracy)\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "3my9kVIo5HwQ",
        "outputId": "8c473e4d-1df5-43e9-ccdd-59745de1f073"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)\n",
            "Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.7)\n",
            "Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.3.2)\n",
            "Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2023.6.3)\n",
            "Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.66.1)\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "[nltk_data] Downloading package movie_reviews to /root/nltk_data...\n",
            "[nltk_data]   Package movie_reviews is already up-to-date!\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Accuracy: 0.834\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "movie_reviews"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ZJVq3phE6GTY",
        "outputId": "dbc0447f-0a2d-4a14-eda2-50cff81724a8"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "<CategorizedPlaintextCorpusReader in '/root/nltk_data/corpora/movie_reviews'>"
            ]
          },
          "metadata": {},
          "execution_count": 10
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "words"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "KWsuane1KraE",
        "outputId": "49e1b5ae-96cb-4dc5-94b4-a965e0cad24a"
      },
      "execution_count": 40,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "['amiga',\n",
              " 'sé',\n",
              " 'sólo',\n",
              " 'vives',\n",
              " 'sabe',\n",
              " 've',\n",
              " 'suplicarle',\n",
              " 'boca',\n",
              " 'diga',\n",
              " 'confesado',\n",
              " 'copas',\n",
              " 'piel',\n",
              " 'sueña',\n",
              " 'noche',\n",
              " 'enloqueces',\n",
              " 'cada',\n",
              " 'botón',\n",
              " 'desabrochas',\n",
              " 'pensando',\n",
              " 'manos',\n",
              " 'visto',\n",
              " 'temblar',\n",
              " 'esperando',\n",
              " 'palabra',\n",
              " 'algún',\n",
              " 'gesto',\n",
              " 'abrazo',\n",
              " 've',\n",
              " 'suspirando',\n",
              " 'ojitos',\n",
              " 'abiertos',\n",
              " 'par',\n",
              " 'par',\n",
              " 'escucharme',\n",
              " 'nombrarle',\n",
              " 'ay',\n",
              " 'amiga',\n",
              " 'sé',\n",
              " 'amiga',\n",
              " 'sé',\n",
              " 'decir',\n",
              " 'hacer',\n",
              " 'verte',\n",
              " 'feliz',\n",
              " 'ojalá',\n",
              " 'pudiera',\n",
              " 'mandar',\n",
              " 'alma',\n",
              " 'libertad',\n",
              " 'hace',\n",
              " 'falta',\n",
              " 'llenarte',\n",
              " 'bolsillos',\n",
              " 'guerras',\n",
              " 'ganadas',\n",
              " 'sueños',\n",
              " 'ilusiones',\n",
              " 'renovadas',\n",
              " 'quiero',\n",
              " 'regalarte',\n",
              " 'poesía',\n",
              " 'piensas',\n",
              " 'dando',\n",
              " 'noticias',\n",
              " 'amiga',\n",
              " 'ojala',\n",
              " 'algún',\n",
              " 'día',\n",
              " 'escuchando',\n",
              " 'canción',\n",
              " 'pronto',\n",
              " 'entiendas',\n",
              " 'nunca',\n",
              " 'quise',\n",
              " 'contar',\n",
              " 'historia',\n",
              " 'pudiera',\n",
              " 'resultar',\n",
              " 'conmovedora',\n",
              " 'perdona',\n",
              " 'amiga',\n",
              " 'inteligencia',\n",
              " 'sabiduría',\n",
              " 'manera',\n",
              " 'decir',\n",
              " 'cosas',\n",
              " 'trabajo',\n",
              " 'idioma',\n",
              " 'amiga',\n",
              " 'princesa',\n",
              " 'cuento',\n",
              " 'infinito',\n",
              " 'amiga',\n",
              " 'tan',\n",
              " 'sólo',\n",
              " 'pretendo',\n",
              " 'cuentes',\n",
              " 'conmigo',\n",
              " 'amiga',\n",
              " 'ver',\n",
              " 'si',\n",
              " 'días',\n",
              " 'fin',\n",
              " 'aprendo',\n",
              " 'hablar',\n",
              " 'tener',\n",
              " 'dar',\n",
              " 'tantos',\n",
              " 'rodeos',\n",
              " 'toda',\n",
              " 'historia',\n",
              " 'importa',\n",
              " 'amiga',\n",
              " 'oh',\n",
              " 'amiga',\n",
              " 'sé',\n",
              " 'sólo',\n",
              " 'vives',\n",
              " 'sabe',\n",
              " 've',\n",
              " 'suplicarle',\n",
              " 'boca',\n",
              " 'diga',\n",
              " 'confesado',\n",
              " 'copas',\n",
              " 'piel',\n",
              " 'sueña',\n",
              " 'noche',\n",
              " 'amiga',\n",
              " 'sé',\n",
              " 'decir',\n",
              " 'hacer',\n",
              " 'verte',\n",
              " 'feliz',\n",
              " 'ojalá',\n",
              " 'pudiera',\n",
              " 'mandar',\n",
              " 'alma',\n",
              " 'libertad',\n",
              " 'hace',\n",
              " 'falta',\n",
              " 'llenarte',\n",
              " 'bolsillos',\n",
              " 'guerras',\n",
              " 'ganadas',\n",
              " 'sueños',\n",
              " 'ilusiones',\n",
              " 'renovadas',\n",
              " 'quiero',\n",
              " 'regalarte',\n",
              " 'poesía',\n",
              " 'piensas',\n",
              " 'dando',\n",
              " 'noticias',\n",
              " 'amiga',\n",
              " 'princesa',\n",
              " 'cuento',\n",
              " 'infinito',\n",
              " 'amiga',\n",
              " 'tan',\n",
              " 'sólo',\n",
              " 'pretendo',\n",
              " 'cuentes',\n",
              " 'conmigo',\n",
              " 'amiga',\n",
              " 'ver',\n",
              " 'si',\n",
              " 'días',\n",
              " 'fin',\n",
              " 'aprendo',\n",
              " 'hablar',\n",
              " 'tener',\n",
              " 'dar',\n",
              " 'tantos',\n",
              " 'rodeos',\n",
              " 'toda',\n",
              " 'historia',\n",
              " 'importa',\n",
              " 'amiga',\n",
              " 'amiga',\n",
              " 'princesa',\n",
              " 'cuento',\n",
              " 'infinito',\n",
              " 'amiga',\n",
              " 'tan',\n",
              " 'sólo',\n",
              " 'pretendo',\n",
              " 'cuentes',\n",
              " 'conmigo',\n",
              " 'amiga',\n",
              " 'ver',\n",
              " 'si',\n",
              " 'días',\n",
              " 'fin',\n",
              " 'aprendo',\n",
              " 'hablar',\n",
              " 'tener',\n",
              " 'dar',\n",
              " 'tantos',\n",
              " 'rodeos',\n",
              " 'toda',\n",
              " 'historia',\n",
              " 'importa',\n",
              " 'amiga',\n",
              " 'oh',\n",
              " 'yeah',\n",
              " 'tiritas',\n",
              " 'pa',\n",
              " 'corazón',\n",
              " 'partió',\n",
              " 'frío',\n",
              " 'tiritas',\n",
              " 'pa',\n",
              " 'corazón',\n",
              " 'partió',\n",
              " 'pa',\n",
              " 'corazón',\n",
              " 'partió',\n",
              " 'ves',\n",
              " 'dos',\n",
              " 'tres',\n",
              " 'vida',\n",
              " 'va',\n",
              " 'viene',\n",
              " 'detiene',\n",
              " 'sé',\n",
              " 'miénteme',\n",
              " 'aunque',\n",
              " 'dime',\n",
              " 'queda',\n",
              " 'dos',\n",
              " 'habitación',\n",
              " 'nunca',\n",
              " 'sale',\n",
              " 'sol',\n",
              " 'existe',\n",
              " 'tiempo',\n",
              " 'dolor',\n",
              " 'llévame',\n",
              " 'si',\n",
              " 'quieres',\n",
              " 'perder',\n",
              " 'ningún',\n",
              " 'destino',\n",
              " 'ningún',\n",
              " 'sé',\n",
              " 'corazón',\n",
              " 've',\n",
              " 'corazón',\n",
              " 'corazón',\n",
              " 'miente',\n",
              " 'amor',\n",
              " 'sabes',\n",
              " 'profundo',\n",
              " 'alma',\n",
              " 'sigue',\n",
              " 'aquel',\n",
              " 'dolor',\n",
              " 'creer',\n",
              " 'ilusión',\n",
              " 'bello',\n",
              " 'vivir',\n",
              " 'curaste',\n",
              " 'herido',\n",
              " 'si',\n",
              " 'hoy',\n",
              " 'dejas',\n",
              " 'nuevo',\n",
              " 'corazón',\n",
              " 'partió',\n",
              " 'quién',\n",
              " 'va',\n",
              " 'entregar',\n",
              " 'emociones',\n",
              " 'va',\n",
              " 'pedir',\n",
              " 'nunca',\n",
              " 'abandone',\n",
              " 'tapará',\n",
              " 'noche',\n",
              " 'si',\n",
              " 'hace',\n",
              " 'frío',\n",
              " 'va',\n",
              " 'curar',\n",
              " 'corazón',\n",
              " 'partió',\n",
              " 'llenará',\n",
              " 'primaveras',\n",
              " 'enero',\n",
              " 'bajará',\n",
              " 'luna',\n",
              " 'juguemos',\n",
              " 'dime',\n",
              " 'si',\n",
              " 'vas',\n",
              " 'dime',\n",
              " 'cariño',\n",
              " 'va',\n",
              " 'curar',\n",
              " 'corazón',\n",
              " 'partió',\n",
              " 'quién',\n",
              " 'va',\n",
              " 'curar',\n",
              " 'dar',\n",
              " 'solamente',\n",
              " 'aquello',\n",
              " 'sobra',\n",
              " 'nunca',\n",
              " 'compartir',\n",
              " 'sino',\n",
              " 'dar',\n",
              " 'limosna',\n",
              " 'amor',\n",
              " 'si',\n",
              " 'sabes',\n",
              " 'digo',\n",
              " 'después',\n",
              " 'tormenta',\n",
              " 'siempre',\n",
              " 'llega',\n",
              " 'calma',\n",
              " 'sé',\n",
              " 'después',\n",
              " 'después',\n",
              " 'curaste',\n",
              " 'herido',\n",
              " 'si',\n",
              " 'hoy',\n",
              " 'dejas',\n",
              " 'nuevo',\n",
              " 'corazón',\n",
              " 'partió',\n",
              " 'va',\n",
              " 'entregar',\n",
              " 'emociones',\n",
              " 'va',\n",
              " 'pedir',\n",
              " 'nunca',\n",
              " 'abandone',\n",
              " 'tapará',\n",
              " 'noche',\n",
              " 'si',\n",
              " 'hace',\n",
              " 'frío',\n",
              " 'va',\n",
              " 'curar',\n",
              " 'corazón',\n",
              " 'partió',\n",
              " 'llenará',\n",
              " 'primaveras',\n",
              " 'enero',\n",
              " 'bajará',\n",
              " 'luna',\n",
              " 'juguemos',\n",
              " 'dime',\n",
              " 'si',\n",
              " 'vas',\n",
              " 'dime',\n",
              " 'cariño',\n",
              " 'va',\n",
              " 'curar',\n",
              " 'corazón',\n",
              " 'partió',\n",
              " 'va',\n",
              " 'entregar',\n",
              " 'emociones',\n",
              " 'va',\n",
              " 'pedir',\n",
              " 'nunca',\n",
              " 'abandone',\n",
              " 'tapará',\n",
              " 'noche',\n",
              " 'si',\n",
              " 'hace',\n",
              " 'frío',\n",
              " 'va',\n",
              " 'curar',\n",
              " 'corazón',\n",
              " 'partió',\n",
              " 'llenará',\n",
              " 'primaveras',\n",
              " 'enero',\n",
              " 'bajará',\n",
              " 'luna',\n",
              " 'juguemos',\n",
              " 'dime',\n",
              " 'si',\n",
              " 'vas',\n",
              " 'dime',\n",
              " 'cariño',\n",
              " 'va',\n",
              " 'curar',\n",
              " 'corazón',\n",
              " 'partió',\n",
              " 'va',\n",
              " 'entregar',\n",
              " 'emociones',\n",
              " 'va',\n",
              " 'pedir',\n",
              " 'nunca',\n",
              " 'abandone',\n",
              " 'tapará',\n",
              " 'noche',\n",
              " 'si',\n",
              " 'hace',\n",
              " 'frío',\n",
              " 'va',\n",
              " 'curar',\n",
              " 'corazón',\n",
              " 'partió',\n",
              " 'llenará',\n",
              " 'primaveras',\n",
              " 'enero',\n",
              " 'bajará',\n",
              " 'luna',\n",
              " 'juguemos',\n",
              " 'dime',\n",
              " 'si',\n",
              " 'vas',\n",
              " 'dime',\n",
              " 'cariño',\n",
              " 'va',\n",
              " 'curar',\n",
              " 'corazón',\n",
              " 'partió',\n",
              " 'bajará',\n",
              " 'luna',\n",
              " 'juguemos',\n",
              " 'llenará',\n",
              " 'primaveras',\n",
              " 'enero',\n",
              " 'va',\n",
              " 'curar',\n",
              " 'juguemos',\n",
              " 'dime',\n",
              " 'si',\n",
              " 'vas',\n",
              " 'cariño',\n",
              " 'va',\n",
              " 'entregar',\n",
              " 'emociones',\n",
              " 'va',\n",
              " 'pedir',\n",
              " 'nunca',\n",
              " 'abandone',\n",
              " 'tapará',\n",
              " 'noche',\n",
              " 'si',\n",
              " 'hace',\n",
              " 'frío',\n",
              " 'va',\n",
              " 'curar',\n",
              " 'corazón',\n",
              " 'partió',\n",
              " 'llenará',\n",
              " 'primaveras',\n",
              " 'enero',\n",
              " 'bajará',\n",
              " 'luna',\n",
              " 'juguemos',\n",
              " 'dime',\n",
              " 'si',\n",
              " 'vas',\n",
              " 'dime',\n",
              " 'cariño',\n",
              " 'va',\n",
              " 'curar',\n",
              " 'corazón',\n",
              " 'partió',\n",
              " 'va',\n",
              " 'entregar',\n",
              " 'emociones',\n",
              " 'va',\n",
              " 'pedir',\n",
              " 'nunca',\n",
              " 'abandone',\n",
              " 'tapará',\n",
              " 'noche',\n",
              " 'si',\n",
              " 'hace',\n",
              " 'frío',\n",
              " 'va',\n",
              " 'curar',\n",
              " 'corazón',\n",
              " 'partió',\n",
              " 'llenará',\n",
              " 'primaveras',\n",
              " 'enero',\n",
              " 'bajará',\n",
              " 'luna',\n",
              " 'juguemos',\n",
              " 'dime',\n",
              " 'si',\n",
              " 'vas',\n",
              " 'dime',\n",
              " 'cariño',\n",
              " 'va',\n",
              " 'curar',\n",
              " 'corazón',\n",
              " 'partió',\n",
              " 'tal',\n",
              " 'va',\n",
              " 'día',\n",
              " 'noche',\n",
              " 'bonita',\n",
              " 'ciudad',\n",
              " 'ir',\n",
              " 'vacaciones',\n",
              " 'hotel',\n",
              " 'verdad',\n",
              " 'tan',\n",
              " 'romántico',\n",
              " 'lujoso',\n",
              " 'publicidad',\n",
              " 'playas',\n",
              " 'fotos',\n",
              " 'madrid',\n",
              " 'lloviendo',\n",
              " 'sigue',\n",
              " 'siempre',\n",
              " 'solamente',\n",
              " 'tiempo',\n",
              " 'pasa',\n",
              " 'lentamente',\n",
              " 'loco',\n",
              " 'vuelvas',\n",
              " 'hace',\n",
              " 'irás',\n",
              " 'enamorar',\n",
              " 'allí',\n",
              " 'prometiste',\n",
              " 'favor',\n",
              " 'puedas',\n",
              " 'llámame',\n",
              " 'soledad',\n",
              " 'llevamos',\n",
              " 'bien',\n",
              " 'paso',\n",
              " 'día',\n",
              " 'planeando',\n",
              " 'encuentro',\n",
              " 'imaginario',\n",
              " 'besaré',\n",
              " 'nadie',\n",
              " 'mundo',\n",
              " 'besó',\n",
              " 'amaré',\n",
              " 'cuerpo',\n",
              " 'mente',\n",
              " 'piel',\n",
              " 'corazón',\n",
              " 'vuelve',\n",
              " 'pronto',\n",
              " 'esperamos',\n",
              " 'soledad',\n",
              " 'besaré',\n",
              " 'nadie',\n",
              " 'mundo',\n",
              " 'besó',\n",
              " 'amaré',\n",
              " 'cuerpo',\n",
              " 'mente',\n",
              " 'piel',\n",
              " 'corazón',\n",
              " 'vuelve',\n",
              " 'pronto',\n",
              " 'esperamos',\n",
              " 'soledad',\n",
              " 'entretengo',\n",
              " 'sé',\n",
              " 'esperando',\n",
              " 'alguien',\n",
              " 'dile',\n",
              " 'debe',\n",
              " 'hablar',\n",
              " 'bajo',\n",
              " 'dicho',\n",
              " 'tardes',\n",
              " 'solo',\n",
              " 'último',\n",
              " 'favor',\n",
              " 'pido',\n",
              " 'colgar',\n",
              " 'dile',\n",
              " 'cuide',\n",
              " 'prometes',\n",
              " 'harás',\n",
              " 'ahora',\n",
              " 'cálmate',\n",
              " 'note',\n",
              " 'llorado',\n",
              " 'disimula',\n",
              " 'bien',\n",
              " 'hago',\n",
              " 'mientras',\n",
              " 'seguiré',\n",
              " 'pensando',\n",
              " 'encuentro',\n",
              " 'imaginario',\n",
              " 'besaré',\n",
              " 'nadie',\n",
              " 'mundo',\n",
              " 'besó',\n",
              " 'amaré',\n",
              " 'cuerpo',\n",
              " 'mente',\n",
              " 'piel',\n",
              " 'corazón',\n",
              " 'vuelve',\n",
              " 'pronto',\n",
              " 'esperamos',\n",
              " 'soledad',\n",
              " 'nadie',\n",
              " 'mundo',\n",
              " 'besó',\n",
              " 'amaré',\n",
              " 'piel',\n",
              " 'corazón',\n",
              " 'soledad',\n",
              " 'besaré',\n",
              " 'nadie',\n",
              " 'mundo',\n",
              " 'besó',\n",
              " 'amaré',\n",
              " 'cuerpo',\n",
              " 'mente',\n",
              " 'piel',\n",
              " 'corazón',\n",
              " 'vuelve',\n",
              " 'pronto',\n",
              " 'esperamos',\n",
              " 'soledad',\n",
              " 'ahora',\n",
              " 'crujen',\n",
              " 'patas',\n",
              " 'mecedora',\n",
              " 'nieve',\n",
              " 'televisor',\n",
              " 'ahora',\n",
              " 'llueve',\n",
              " 'sala',\n",
              " 'apagan',\n",
              " 'velas',\n",
              " 'cielo',\n",
              " 'iluminó',\n",
              " 'ahora',\n",
              " 'corren',\n",
              " 'lentos',\n",
              " 'derramando',\n",
              " 'trova',\n",
              " 'mundo',\n",
              " 'despertó',\n",
              " 'ahora',\n",
              " 'truena',\n",
              " 'silencio',\n",
              " 'feroz',\n",
              " 'ahora',\n",
              " 'entra',\n",
              " 'tos',\n",
              " 'ahora',\n",
              " 'hallamos',\n",
              " 'tiempo',\n",
              " 'podemos',\n",
              " 'mirarnos',\n",
              " 'detrás',\n",
              " 'rencor',\n",
              " 'ahora',\n",
              " 'enseño',\n",
              " 'dónde',\n",
              " 'vengo',\n",
              " 'piezas',\n",
              " 'rotas',\n",
              " 'motor',\n",
              " 'ahora',\n",
              " 'encuentro',\n",
              " 'puerto',\n",
              " 'ahora',\n",
              " 'encuentro',\n",
              " 'duda',\n",
              " 'feroz',\n",
              " 'ahora',\n",
              " 'enseño',\n",
              " 'dónde',\n",
              " 'vengo',\n",
              " 'hecho',\n",
              " 'corazón',\n",
              " 'vengo',\n",
              " 'aire',\n",
              " 'secaba',\n",
              " 'piel',\n",
              " 'amor',\n",
              " 'calle',\n",
              " 'encontraste',\n",
              " 'compares',\n",
              " 'bajé',\n",
              " 'tierra',\n",
              " 'pincel',\n",
              " 'imperdonable',\n",
              " 'parezco',\n",
              " 'nadie',\n",
              " 'ahora',\n",
              " 'saltan',\n",
              " 'gatos',\n",
              " 'buscando',\n",
              " 'sobras',\n",
              " 'maúllas',\n",
              " 'triste',\n",
              " 'canción',\n",
              " 'ahora',\n",
              " 'quedao',\n",
              " 'palabras',\n",
              " 'comparas',\n",
              " 'comparas',\n",
              " 'tanta',\n",
              " 'pasión',\n",
              " 'ahora',\n",
              " 'podemos',\n",
              " 'mirarnos',\n",
              " 'miedo',\n",
              " 'reﬂejo',\n",
              " 'retrovisor',\n",
              " 'ahora',\n",
              " 'enseño',\n",
              " 'dónde',\n",
              " 'vengo',\n",
              " 'heridas',\n",
              " 'dejó',\n",
              " 'amor',\n",
              " 'ahora',\n",
              " 'quiero',\n",
              " 'aspavientos',\n",
              " 'tan',\n",
              " 'solo',\n",
              " 'charla',\n",
              " 'tranquila',\n",
              " 'si',\n",
              " 'quieres',\n",
              " 'cuento',\n",
              " 'quiero',\n",
              " 'si',\n",
              " 'quieres',\n",
              " 'cuento',\n",
              " 'vengo',\n",
              " 'aire',\n",
              " 'secaba',\n",
              " 'piel',\n",
              " 'amor',\n",
              " 'calle',\n",
              " 'encontraste',\n",
              " 'compares',\n",
              " 'bajé',\n",
              " 'tierra',\n",
              " 'pincel',\n",
              " 'imperdonable',\n",
              " 'parezco',\n",
              " 'nadie',\n",
              " 'alguien',\n",
              " 'seque',\n",
              " 'piel',\n",
              " 'amor',\n",
              " 'desclaven',\n",
              " 'borren',\n",
              " 'sien',\n",
              " 'hables',\n",
              " 'alguien',\n",
              " 'seque',\n",
              " 'piel',\n",
              " 'amor',\n",
              " 'desclaven',\n",
              " 'alma',\n",
              " 'aire',\n",
              " 'compares',\n",
              " 'separen',\n",
              " 'si',\n",
              " 'pueden',\n",
              " 'separen',\n",
              " 'intenten',\n",
              " 'separen',\n",
              " 'intenten',\n",
              " 'alma',\n",
              " 'suerte',\n",
              " 'si',\n",
              " 'pueden',\n",
              " 'desclaven',\n",
              " 'intenten',\n",
              " 'intenten',\n",
              " 'separen',\n",
              " 'intenten',\n",
              " 'alma',\n",
              " 'suerte',\n",
              " 'alma',\n",
              " 'alma',\n",
              " 'suerte',\n",
              " 'acerques',\n",
              " 'matando',\n",
              " 'responden',\n",
              " 'manos',\n",
              " 'vivo',\n",
              " 'intento',\n",
              " 'poder',\n",
              " 'apagar',\n",
              " 'hoguera',\n",
              " 'cada',\n",
              " 'risa',\n",
              " 'dolor',\n",
              " 'amargo',\n",
              " 'dejas',\n",
              " 'pintado',\n",
              " 'fin',\n",
              " 'cada',\n",
              " 'abrazo',\n",
              " 'quiero',\n",
              " 'vino',\n",
              " 'aparecer',\n",
              " 'dije',\n",
              " 'espera',\n",
              " 'si',\n",
              " 'escucho',\n",
              " 'voz',\n",
              " 'tan',\n",
              " 'solo',\n",
              " 'suspiro',\n",
              " 'enciendes',\n",
              " 'luces',\n",
              " 'apagar',\n",
              " 'ay',\n",
              " 'vayas',\n",
              " 'acabe',\n",
              " 'vino',\n",
              " 'quieres',\n",
              " 'quedar',\n",
              " 'muero',\n",
              " 'callar',\n",
              " 'tan',\n",
              " 'solo',\n",
              " 'muero',\n",
              " 'ganas',\n",
              " 'comerte',\n",
              " 'besos',\n",
              " 'muero',\n",
              " 'sé',\n",
              " 'manías',\n",
              " 'grandes',\n",
              " 'miedos',\n",
              " 'ciudad',\n",
              " 'perfecta',\n",
              " 'viejos',\n",
              " 'guardé',\n",
              " 'esquina',\n",
              " 'sofá',\n",
              " 'si',\n",
              " 'vuelves',\n",
              " 'luego',\n",
              " 'si',\n",
              " 'escucho',\n",
              " 'voz',\n",
              " 'tan',\n",
              " 'solo',\n",
              " 'suspiro',\n",
              " 'enciendes',\n",
              " 'luces',\n",
              " 'apagar',\n",
              " 'ay',\n",
              " 'vayas',\n",
              " 'acabe',\n",
              " 'vino',\n",
              " 'vayas',\n",
              " 'quieres',\n",
              " 'quedar',\n",
              " 'muero',\n",
              " 'callar',\n",
              " 'tan',\n",
              " 'solo',\n",
              " 'muero',\n",
              " 'ganas',\n",
              " 'comerte',\n",
              " 'besos',\n",
              " 'muero',\n",
              " 'gastan',\n",
              " 'días',\n",
              " 'pierde',\n",
              " 'momento',\n",
              " 'cobardía',\n",
              " 'quema',\n",
              " 'dentro',\n",
              " 'salen',\n",
              " 'ganas',\n",
              " 'perdimos',\n",
              " 'tiempo',\n",
              " 'ganó',\n",
              " 'silencio',\n",
              " 'miedo',\n",
              " 'cuento',\n",
              " 'miedo',\n",
              " 'cuento',\n",
              " 'muero',\n",
              " 'callar',\n",
              " 'tan',\n",
              " 'solo',\n",
              " 'muero',\n",
              " 'ganas',\n",
              " 'comerte',\n",
              " 'besos',\n",
              " 'muero',\n",
              " 'ay',\n",
              " 'muero',\n",
              " 'aguantar',\n",
              " 'tan',\n",
              " 'solo',\n",
              " 'muero',\n",
              " 'ganas',\n",
              " 'comerte',\n",
              " 'besos',\n",
              " 'muero',\n",
              " 'muero',\n",
              " 'muero',\n",
              " 'mírame',\n",
              " 'consigo',\n",
              " 'concentrar',\n",
              " 'ando',\n",
              " 'despistado',\n",
              " 'hago',\n",
              " 'mal',\n",
              " 'desastre',\n",
              " 'sé',\n",
              " 'pasando',\n",
              " 'gustas',\n",
              " 'rabiar',\n",
              " 'deseo',\n",
              " 'llegas',\n",
              " 'desesperar',\n",
              " 'tan',\n",
              " 'grande',\n",
              " 'siento',\n",
              " 'tenerte',\n",
              " 'bastará',\n",
              " 'invita',\n",
              " 'vivir',\n",
              " 'da',\n",
              " 'ilusión',\n",
              " 'fuerza',\n",
              " 'une',\n",
              " 'dos',\n",
              " 'dos',\n",
              " 'fuerza',\n",
              " 'corazón',\n",
              " 'hace',\n",
              " 'abrace',\n",
              " 'cuerpos',\n",
              " 'lleguen',\n",
              " 'estorbar',\n",
              " 'tiemblo',\n",
              " 'solo',\n",
              " 'idea',\n",
              " 'rozar',\n",
              " 'labios',\n",
              " 'llenos',\n",
              " 'besos',\n",
              " 'nuevos',\n",
              " 'puedo',\n",
              " 'dormir',\n",
              " 'robas',\n",
              " 'tranquilidad',\n",
              " 'alguien',\n",
              " 'bordado',\n",
              " 'cuerpo',\n",
              " 'hilos',\n",
              " 'ansiedad',\n",
              " 'cinturón',\n",
              " 'piernas',\n",
              " 'cruzadas',\n",
              " 'espalda',\n",
              " 'reloj',\n",
              " 'dedos',\n",
              " 'agujas',\n",
              " 'dan',\n",
              " 'cuerda',\n",
              " 'motor',\n",
              " 'fuerza',\n",
              " 'corazón',\n",
              " 'fuerza',\n",
              " 'lleva',\n",
              " 'empuja',\n",
              " 'llena',\n",
              " 'arrastra',\n",
              " 'acerca',\n",
              " 'dios',\n",
              " 'sentimiento',\n",
              " 'casi',\n",
              " 'obsesión',\n",
              " 'si',\n",
              " 'fuerza',\n",
              " 'corazón',\n",
              " 'lía',\n",
              " 'descarga',\n",
              " 'energía',\n",
              " 'va',\n",
              " 'quitando',\n",
              " ...]"
            ]
          },
          "metadata": {},
          "execution_count": 40
        }
      ]
    }
  ]
}